services:
  - type: web
    name: eye-disease-backend
    env: python
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn backend.app:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
    autoDeploy: true

  - type: web
    name: eye-disease-frontend
    env: node
    plan: free
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "npx serve -s frontend/build"
    autoDeploy: true
